---
- name: Install build-essential
  apt: pkg=build-essential

- name: Install curl
  apt: pkg=curl

- name: Install Perl dependencies
  shell: curl -L cpanmin.us | perl - Mojolicious Modern::Perl DBIx::Class DBIx::Class::Migration DateTime DateTime::Format::SQLite --force
